name: .NET Backend CI/CD
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Frontend Artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.MY_GITHUB_PAT }}
          repo: d4n1elliu/EduMap
          workflow: frontend-deploy.yml
          name: frontend-dist
          path: ./wwwroot

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' # Matches your project settings

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'EduMap'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
          clean: false